version: '3.4'
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16
services:
  wifi.dnp.dappnode.eth:
    image: 'wifi.dnp.dappnode.eth:0.2.2'
    container_name: DAppNodeCore-wifi.dnp.dappnode.eth
    build: ./build
    environment:
      - SSID=DAppNodeWIFI
      - WPA_PASSPHRASE=dappnode
      - NAT=true
      - CHANNEL=11
      - MODE=admin
      - INTERFACE
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    dns: 172.33.1.2
    privileged: true
    restart: always
    networks:
      network:
        ipv4_address: 172.33.1.10
    logging:
      options:
        max-size: 10m
        max-file: '3'
